name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
    - name: Set up Maven settings
      uses: whelk-io/maven-settings-xml-action@v22
      with:
        servers: >
          [
            { "id": "bloomreach-maven2-enterprise", "username": "${{ secrets.BLOOMREACH_USER }}", "password": "${{ secrets.BLOOMREACH_PASSWORD }}" }
          ]
    - name: Build with Maven
      run: mvn -B package --file pom.xml
